<?php

$arr = array( 'AHEC' => 'Alternate Hydro Energy Centre',
    'ASED' => 'Applied Science and Engineering Department',
    'CNT' => 'Centre for Nanotechnology',
    'ARCD' => 'Architecture Department' ,
    'BTD' => 'Biotechnology Department' ,
    'CHED' => 'Chemical Engineering Department',
    'CDM' =>  'Centre of Excellence in Disaster Mitigation and Management',
    'CYD' => 'Chemistry Department' ,
    'CED' => 'Civil Engineering Department' ,
    'CSED' => 'Computer Science and Engineering Department' ,
    'CT' => 'Centre for Transportation Systems' ,
    'EQD' => 'Earthquake Department' ,
    'ESD' => 'Earth Sciences Department' ,
    'EED' => 'Electrical Engineering Department' ,
    'ECED' =>  'Electronics and Communication Engineering Department' ,
    'HSD' => 'Humanities and Social Sciences Department' ,
    'HYD' => 'Hydrology Department',
    'MSD' => 'Management Studies Department' ,
    'MAD' => 'Mathematics Department' ,
    'MIED' => 'Mechanical and Industrial Engineering Department' ,
    'MMED' => 'Metallurgical and Materials Engineering Department' ,
    'PTD' => 'Paper Technology Department' ,
    'PPED' => 'Polymer and Process Engineering Department' ,
    'PHD' => 'Physics Department' ,
    'WRDMD' => 'Water Resources Development and Management Department' ,
    'CDM' => 'Centre for Disaster Mitigation' ,
    'ICC' => 'Institute Computer Centre' ,
    'IIC' => 'Institute Instrumentation Centre' ,
    'QIP' =>  'Quality Improvement Programme' ,
    'ISC' =>  'Information Superhighway Centre' ,
    'RO'  =>  'Registrar Office'
    )
?>
