from django.conf.urls import url, patterns
from buysell.views import *

urlpatterns = patterns('',
    url(r'^$',buysell),
    url(r'^sell/$', sell),
    url(r'^request-item/$', request_item),
    url(r'^buy()()/$', buy, name='none'),
    url(r'^buy/(?P<mc>\w+)/?$', buy, name='main category'),
    url(r'^buy/(?P<mc>\w+)/(?P<sc>\w+)/?$', buy, name='sub category'),
    url(r'^buy/([A-Z]{0,2})()()()/$', buy),
    url(r'^buy/([A-Z]{0,2})/()([^/]+)()/$', buy),
    url(r'^buy/([A-Z]{0,2})/()([^/]+)/([^/]+)/$', buy),
    url(r'^buy/([A-Z]{2})/([A-Z]{2})()()/$', buy),
    url(r'^buy/([A-Z]{2})/([A-Z]{0,2})/([^/]+)()/$', buy),
    url(r'^buy/([A-Z]{2})/([A-Z]{0,2})/([^/]+)/([^/]+)/$', buy),
    url(r'^search/$',search),
#    url(r'^search/([^/]+)/([^/]+)()()/$', search),
#    url(r'^search/([^/]+)/([^/]+)/([^/]+)()/$', search),
#    url(r'^search/([^/]+)/([^/]+)/([^/]+)/([^/]+)/$', search),
    url(r'^sendmail/([^/]+)/([^/]+)/$', sendmail),
    url(r'^viewrequests/$', viewrequests),
    url(r'^(viewrequests)/()([^/]+)()/$', search),
    url(r'^(viewrequests)/()([^/]+)/([^/]+)/$', search),
    url(r'^my-account/$', my_account),
    url(r'^ajax-request/([^/]+)/$', ajax_request),
    url(r'^edit/([^/]+)/([^/]+)/$', edit),
    url(r'^editsave/([^/]+)/([^/]+)/$', editsave),
    url(r'^delete/([^/]+)/([^/]+)/$', deleteEntry),
    url(r'^requested_item_details/(?P<item_id>\w+)/?$',requested_item_details),
    url(r'^buy_item_details/(?P<item_id>\w+)/?$',buy_item_details),
)
