ARTIST_PIC_DIR = '/home/songsmedia/artist'
ALBUMART_DIR = '/home/songsmedia/albumart'
SONG_DIR = '/home/pankaj/jukebox_songs/newestsongs/'
SONGS_JSON_FILE = '/home/pankaj/channeli/all.json'
ARTISTS_JSON_FILE = '/home/pankaj/channeli/artists.json'
ALBUMS_JSON_FILE = '/home/pankaj/channeli/albums.json'
