ARTIST_PIC_DIR = '/home/songsmedia/'
ALBUMART_DIR = '/home/songsmedia/'
SONG_DIR = '/home/pankaj/jukebox_songs/newestsongs/'
SONGS_JSON_FILE = '/home/pankaj/channeli/songs.json'
ARTISTS_JSON_FILE = '/home/pankaj/channeli/artistsnew.json'
ALBUMS_JSON_FILE = '/home/pankaj/channeli/albumsnew.json'
