SEASON_CHOICES = (
    ('1', 'Autumn Semester'),
    ('2', 'Spring Semester'),
    )

SEMESTER_CHOICES = (
  ('UG10', 'UG(I Year I Semester)'),
  ('UG11', 'UG(I Year II Semester)'),
  ('UG20', 'UG(II Year I Semester)'),
  ('UG21', 'UG(II Year II Semester)'),
  ('UG30', 'UG(III Year I Semester)'),
  ('UG31', 'UG(III Year II Semester)'),
  ('UG40', 'UG(IV Year I Semester)'),
  ('UG41', 'UG(IV Year II Semester)'),
  ('UG50', 'UG(V Year I Semester)'),
  ('UG51', 'UG(V Year II Semester)'),
  ('ST1' , 'Summer Term(I Year)'),
  ('ST2' , 'Summer Term(II Year)'),
  ('ST3' , 'Summer Term(III Year)'),
  ('ST4' , 'Summer Term(IV Year)'),
  ('PG10', 'PG(I Year I Semester)'),
  ('PG11', 'PG(I Year II Semester)'),
  ('PG20', 'PG(II Year I Semester)'),
  ('PG21', 'PG(II Year II Semester)'),
  ('PG30', 'PG(III Year I Semester)'),
  ('PG31', 'PG(III Year II Semester)'),
  ('PHD10', 'PHD(I Year I Semester)'),
  ('PHD11', 'PHD(I Year II Semester)'),
  ('PHD20', 'PHD(II Year I Semester)'),
  ('PHD21', 'PHD(II Year II Semester)'),
  ('PHD30', 'PHD(III Year I Semester)'),
  ('PHD31', 'PHD(III Year II Semester)'),
  ('PHD40', 'PHD(IV Year I Semester)'),
  ('PHD41', 'PHD(IV Year II Semester)'),
  ('PHD50', 'PHD(V Year I Semester)'),
  ('PHD51', 'PHD(V Year II Semester)'),
  ('PHD60', 'PHD(VI Year I Semester)'),
  ('PHD61', 'PHD(VI Year II Semester)'),
  ('PHD70', 'PHD(VII Year I Semester)'),
  ('PHD71', 'PHD(VII Year II Semester)'),
  ('PHD80', 'PHD(VIII Year I Semester)'),
  ('PHD81', 'PHD(VIII Year II Semester)'),
  ('PHD90', 'PHD(IX Year I Semester)'),
  ('PHD91', 'PHD(IX Year II Semester)'),
  )

GRADE_CHOICES = {
    'A+': '10',
    'A' : '9',
    'B+': '8',
    'B' : '7',
    'C+': '6',
    'C' : '5',
    'D' : '4',
    'F' : 'Back',
    '-' : 'NA',
}


