#!/bin/bash

python prod_manage.py collectstatic --noinput
python prod_manage.py cachepages
touch production/wsgi.py

# For building lectut static files
grunt --gruntfile apps/lectut/static/lectut-front/Gruntfile.js build
