#!/bin/bash

python -Wi manage.py collectstatic --settings=settings.common.deploy_settings --noinput
python -Wi manage.py cachepages --settings=settings.common.deploy_settings
touch settings/channeli/wsgi.py

