#!/bin/bash

netstat -netul | awk '{ print $4 }' | awk -F':' '{ print $NF }' | tail -n +3 > temp_netstat

TEMP=temp_netstat
port_server_assign=0

for port in {60000..70000}
do
  flag=1
  while read line
  do
    p=`echo $line | awk '{ print $1 }'`
    if [ $port -eq $p ]
    then
      flag=0
      break
    fi
  done<$TEMP
  if [ $flag -eq 1 ]
  then
    port_server_assign=$port
    break
  fi
done

txtgrn='\e[0;32m'
txtreset='\e[0m'
echo -e "Assigining port ${txtgrn}$port_server_assign${txtreset} to your server"

rm $TEMP

cd /home/`whoami`/channeli && python manage.py runserver_plus 0.0.0.0:$port_server_assign
