CODE_LENGTH=10
TEXT_LENGTH=100
PHONE_NO_LENGTH=15

YES_NO_CHOICES = (
    ('Y', 'Yes'),
    ('N', 'No'),
)

# MAKE SURE ALL APPLICATIONS USE THIS TO SHOW departments.
# It should not contain any number
DEPARTMENT_CHOICES = (
    # End all department names with 'D'
    ('AHEC', 'Alternate Hydro Energy Centre'),
    ('ASED', 'Applied Science and Engineering Department'),
    ('CNT', 'Centre for Nanotechnology'),
    ('ARCD', 'Architecture and Planning Department'),
    ('BTD', 'Biotechnology Department'),
    ('CHED', 'Chemical Engineering Department'),
    ('CDM', 'Centre of Excellence in Disaster Mitigation and Management'),
    ('CYD', 'Chemistry Department'),
    ('CED','Civil Engineering Department'),
    ('CSED','Computer Science and Engineering Department'),
    ('CT', 'Centre for Transportation Systems'),
    ('EQD', 'Earthquake Department'),
    ('ESD', 'Earth Sciences Department'),
    ('EED', 'Electrical Engineering Department'),
    ('ECED', 'Electronics and Communication Engineering Department'),
    ('HSD','Humanities and Social Sciences Department'),
    ('HYD','Hydrology Department'),
    ('MSD','Management Studies Department'),
    ('MAD','Mathematics Department'),
    ('MIED','Mechanical and Industrial Engineering Department'),
    ('MMED','Metallurgical and Materials Engineering Department'),
    ('PTD','Paper Technology Department'),
    ('PPED','Polymer and Process Engineering Department'),
    ('PHD','Physics Department'),
    ('WRDMD','Water Resources Development and Management Department'),
    ('CDM','Centre for Disaster Mitigation'),
    ('ICC', 'Institute Computer Centre'),
    ('IIC', 'Institute Instrumentation Centre'),
    ('QIP', 'Quality Improvement Programme'),
)

SIMPLIFIED_DEPARTMENTS = {
    'AHEC':'Alternate Hydro Energy Centre',
    'ASED':'App. Science and Eng. Department',
    'CNT':'Centre for Nanotechnology',
    'ARCD':'Architecture Department',
    'BTD':'Biotechnology Department',
    'CHED':'Chemical Engineering Department',
    'CDM':'Centre of Disaster Mitigation',
    'CYD':'Chemistry Department',
    'CED':'Civil Engineering Department',
    'CSED':'CSE Department',
    'CT':'Centre for Transportation Systems',
    'EQD':'Earthquake Department',
    'ESD':'Earth Sciences Department',
    'EED':'Electrical Engineering Department',
    'ECED':'ECE Department',
    'HSD':'HS Department',
    'HYD':'Hydrology Department',
    'MSD':'Management Studies Department',
    'MAD':'Mathematics Department',
    'MIED':'MIE Department',
    'MMED':'MME Department',
    'PTD':'Paper Technology Department',
    'PPED':'Polymer and Process Eng. Department',
    'PHD':'Physics Department',
    'WRDMD':'WRDM Department',
    'CDM':'Centre for Disaster Mitigation',
    'ICC':'Institute Computer Centre',
    'IIC':'Institute Instrumentation Centre',
    'QIP':'Quality Improvement Programme',
}

STATE_CHOICES = (
    ('ADP', 'Andhra Pradesh'),
    ('ARP', 'Arunachal Pradesh'),
    ('ASM', 'Assam'),
    ('BHR', 'Bihar'),
    ('CHG', 'Chhattisgarh'),
    ('DEL', 'Delhi'),
    ('GOA', 'Goa'),
    ('GUJ', 'Gujarat'),
    ('HAR', 'Haryana'),
    ('HMP', 'Himachal Pradesh'),
    ('JNK', 'Jammu and Kashmir'),
    ('JHK', 'Jharkhand'),
    ('KAR', 'Karnataka'),
    ('KRL', 'Kerala'),
    ('MDP', 'Madya Pradesh'),
    ('MAH', 'Maharashtra'),
    ('MNP', 'Manipur'),
    ('MGY', 'Meghalaya'),
    ('MIZ', 'Mizoram'),
    ('NGL', 'Nagaland'),
    ('ORS', 'Orissa'),
    ('PJB', 'Punjab'),
    ('RAJ', 'Rajasthan'),
    ('SIK', 'Sikkim'),
    ('TAN', 'Tamil Nadu'),
    ('TLG', 'Telangana'),
    ('TRP', 'Tripura'),
    ('UTA', 'Uttaranchal'),
    ('UTP', 'Uttar Pradesh'),
    ('WSB', 'West Bengal')
)

GRADE_CHOICES = (
    ('A+', '10'),
    ('A', '9'),
    ('B+', '8'),
    ('B', '7'),
    ('C+', '6'),
    ('C', '5'),
    ('D', '4'),
    ('F', 'Back'),
    ('-', 'NA'),
)

# TODO: Fill with real data.
PHD_INFO_SCHEME_CHOICES = (
    ('MHRD', 'MHRD'),
)

# These courses must be in order in which courses can be taken by a student.
# Do not change the order or insert data as the order is used to separate the entries available to UG, PG and PhD.
# If you want to change the order, change the corresponding lines of view placment.views.educational_details also.
SEMESTER_CHOICES = (
  ('UG0' , 'UG Overall'),
  ('DPLM', 'Diploma'),
  ('PG0' , 'PG Overall'),
  ('10TH', 'Tenth'  ),
  ('12TH', 'Twelfth'),
  ('UG10', 'UG(I Year I Semester)'),
  ('UG11', 'UG(I Year II Semester)'),
  ('UG20', 'UG(II Year I Semester)'),
  ('UG21', 'UG(II Year II Semester)'),
  ('UG30', 'UG(III Year I Semester)'),
  ('UG31', 'UG(III Year II Semester)'),
  ('UG40', 'UG(IV Year I Semester)'),
  ('UG41', 'UG(IV Year II Semester)'),
  ('UG50', 'UG(V Year I Semester)'),
  ('UG51', 'UG(V Year II Semester)'),
  ('ST1' , 'Summer Term(I Year)'),
  ('ST2' , 'Summer Term(II Year)'),
  ('ST3' , 'Summer Term(III Year)'),
  ('ST4' , 'Summer Term(IV Year)'),
  ('PG10', 'PG(I Year I Semester)'),
  ('PG11', 'PG(I Year II Semester)'),
  ('PG20', 'PG(II Year I Semester)'),
  ('PG21', 'PG(II Year II Semester)'),
  ('PG30', 'PG(III Year I Semester)'),
  ('PG31', 'PG(III Year II Semester)'),
  ('PHD10', 'PHD(I Year I Semester)'),
  ('PHD11', 'PHD(I Year II Semester)'),
  ('PHD20', 'PHD(II Year I Semester)'),
  ('PHD21', 'PHD(II Year II Semester)'),
  ('PHD30', 'PHD(III Year I Semester)'),
  ('PHD31', 'PHD(III Year II Semester)'),
  ('PHD40', 'PHD(IV Year I Semester)'),
  ('PHD41', 'PHD(IV Year II Semester)'),
  ('PHD50', 'PHD(V Year I Semester)'),
  ('PHD51', 'PHD(V Year II Semester)'),
  ('PHD60', 'PHD(VI Year I Semester)'),
  ('PHD61', 'PHD(VI Year II Semester)'),
  ('PHD70', 'PHD(VII Year I Semester)'),
  ('PHD71', 'PHD(VII Year II Semester)'),
  ('PHD80', 'PHD(VIII Year I Semester)'),
  ('PHD81', 'PHD(VIII Year II Semester)'),
  ('PHD90', 'PHD(IX Year I Semester)'),
  ('PHD91', 'PHD(IX Year II Semester)'),
  ('PHD0' , 'PHD Overall'),
  ('UG00', 'UG(New Entrants)')
  )

# Can consist of : alphabets (small and capital) + digits + dot character(.)
# Important : Corressponding changes in DEGREES below for any change here.
DEGREE_CHOICES = (
    ('B.Tech.','Bachelor of Technology'),
    ('B.Arch.','Bachelor of Architecture'),
    ('IDD', 'Integrated Dual Degree'),
    ('M.Tech.', 'Master of Technology'),
    ('IMT', 'Integrated Master of Technology'),
    ('IMSc', 'Integrated Master of Science'),
    ('M.Arch.', 'Master of Architecture'),
    ('MURP', 'Master of Urban and Regional Planning'),
    ('PGDip', 'Postgraduate Diploma Course'),
    ('MBA', 'Master of Business Administration'),
    ('MCA', 'Master of Computer Applications'),
    ('MSc', 'Master of Sciences'),
    ('PHD', 'Doctor of Philosophy'),
)

SIMPLIFIED_DEGREE = {
  'B.Tech.':'B.Tech.',
  'B.Arch.':'B.Arch.',
  'IDD': 'Int. Dual Degree',
  'M.Tech.': 'M.Tech.',
  'IMT': 'Int. M.Tech.',
  'IMSc': 'Int. M.Sc.',
  'M.Arch.': 'M.Arch.',
  'MURP': 'M.U.R.P.',
  'PGDip': 'P.G. Dip.',
  'MBA': 'MBA',
  'MCA': 'MCA',
  'MSc': 'M.Sc.',
  'PHD': 'Ph.D.',
}

BANK_NAME= (
    ('PNB','Punjab National Bank'),
    ('SBI', 'State Bank Of India'),
)

DEGREES= {
  'UG':['B.Tech.','B.Arch.','IDD','IMT','IMSc'],
  'PG':['M.Tech.','M.Arch.','MURP','PGDip','MBA','MCA','MSc'],
  'PHD':['PHD']
}

GRADUATION_CHOICES = (
    ('UG','Under Graduate'),
    ('PG','Post Graduate'),
    ('PHD','PhD')
)

COURSE_CHANGE_CHOICES = (
  ('ADD', 'Course Added'),
  ('DRP', 'Course Dropped'),
)

BHAWAN_CHOICES = (
    ('AZB','Azad Bhawan'),
    ('CTB','Cautley Bhawan'),
    ('GNB','Ganga Bhawan'),
    ('GVB','Govind Bhawan'),
    ('JWB','Jawahar Bhawan'),
    ('RKB','Radhakrishnan Bhawan'),
    ('RJB','Rajendra Bhawan'),
    ('RGB','Rajiv Bhawan'),
    ('RVB','Ravindra Bhawan'),
    ('MVB','Malviya Bhawan'),
    ('SB','Sarojini Bhawan'),
    ('KB','Kasturba Bhawan'),
    ('IB',' Indra Bhawan'),
    ('DAY','Day Scholar'),
    ('KIH','Khosla International House'),
)

RESIDENTIAL_CHOICES = BHAWAN_CHOICES + (
    ('GPH','GP Hostel'),
    ('MRH','MR Chopra Hostel'),
    ('AZW','Azad Wing Hostel'),
    ('DBH','DS Barrack Hostel'),
    ('AKH','AN Khosla House'),
    ('KIH','Khosla International House'),
    ('NA','Not Applicable'),
)

PHD_INFO_TIME_TYPE_CHOICES = (
    ('FULL', 'Fulltime'),
    ('PART', "Parttime"),
)

SEMESTER_TYPE_CHOICES = (
    ('S', 'Spring'),
    ('A', 'Autumn'),
)

CATEGORY_CHOICES = (
    ('GEN', 'General'),
    ('SC', 'Scheduled Caste'),
    ('ST', 'Scheduled Tribe'),
    ('OBC', 'Other Backward Classes'),
)

MARITAL_STATUS_CHOICES = (
    ('SIN', 'Single'),
    ('MAR', 'Married'),
)

BLOOD_GROUP_CHOICES = (
    ('O+', 'O+'),
    ('O-', 'O-'),
    ('AB+', 'AB+'),
    ('AB-', 'AB-'),
    ('A+', 'A+'),
    ('A-', 'A-'),
    ('B+', 'B+'),
    ('B-', 'B-'),
)

GENDER_CHOICES = (
    ('M', 'Male'),
    ('F', 'Female'),
)

LANGUAGE_CHOICES = (
  ('AB', 'Arabic'),
  ('AS', 'Assamese'),
  ('BN', 'Bangla'),
  ('EN', 'English'),
  ('FR', 'French'),
  ('GM', 'German'),
  ('GJ', 'Gujarati'),
  ('HB', 'Hebrew'),
  ('HN', 'Hindi'),
  ('JA', 'Japanese'),
  ('KD', 'Kannada'),
  ('MM', 'Malyalam'),
  ('MR', 'Marathi'),
  ('NP', 'Nepali'),
  ('OR', 'Oriya'),
  ('PN', 'Punjabi'),
  ('RU', 'Russian'),
  ('SN', 'Sanskrit'),
  ('SP', 'Spanish'),
  ('SW', 'Swahili'),
  ('TM', 'Tamil'),
  ('TG', 'Telugu'),
  ('UD', 'Urdu'),
)


def get_integer_tuple(lower_bound, upper_bound):
  """Can use it to generate a drop down list of integers.
     The model field should be of type IntegerField and NOT CharField."""
  l = []
  for x in range(lower_bound, upper_bound):
    l.append((x,x))
  return tuple(l)

def get_value_from_key(choices, key):
  """Use this function to get the value of a choices tuple, given the key."""
  for tup in choices:
    if tup[0] == key:
      return tup[1]
  return None

PRIORITY_CHOICES = get_integer_tuple(1, 25)
import datetime
year = datetime.datetime.now().year
HISTORY_YEAR_CHOICES = get_integer_tuple(year - 100, year + 1)
FUTURE_YEAR_CHOICES = get_integer_tuple(year, year + 10)

# Bug Tracker Constats

BUG_TYPES = (
  ('bug', 'Bug'),
  ('doc', 'Doc'),
  ('feedback', 'Feedback'),
  ('imporvement', 'Improvement'),
  ('newfeat', 'New Feature'),
  )

BUG_STATUS = (
  ('new', 'New'),
  ('assigned', 'Assigned'),
  ('resolved', 'Resolved'),
  ('closed', 'Closed'),
  )

RAILWAY_CHOICES = (
    ('ABR', 'ABU ROAD - ABR'),
    ('AGC', 'AGRA CANTT - AGC'),
    ('AF', 'AGRA FORT - AF'),
    ('AGA', 'AGRA CITY - AGA'),
    ('ADI', 'AHMEDABAD JN - ADI'),
    ('AII', 'AJMER - AII'),
    ('AK', 'AKOLA - AK'),
    ('ALJN', 'ALIGARH JN - ALJN'),
    ('ALD', 'ALLAHABAD - ALD'),
    ('ALLP', 'ALLEPPEY - ALLP'),
    ('AWR', 'ALWAR - AWR'),
    ('AWY', 'ALWAYE - AWY'),
    ('UMB', 'AMBALA - UMB'),
    ('AME', 'AMETHI - AME'),
    ('AMI', 'AMRAVATI - AMI'),
    ('ASR', 'AMRITSAR - ASR'),
    ('ASN', 'ASANSOL JN - ASN'),
    ('AWB', 'AURANGABAD - AWB'),
    ('AMH', 'AZAMGARH - AMH'),
    ('BRK', 'BAHRAICH - BRK'),
    ('SBC', 'BANGALORE - SBC'),
    ('BUI', 'BALLIA - BUI'),
    ('BWT', 'BANGARAPET - BWT'),
    ('BP', 'BARRACKPORE - BP'),
    ('BJU', 'BARAUNI JN - BJU'),
    ('BE', 'BAREILLY - BE'),
    ('BST', 'BASTI - BST'),
    ('BSL', 'BHUSAVAL - BSL'),
    ('BGS', 'BEGU SARAI - BGS'),
    ('BGM', 'BELGAUM - BGM'),
    ('BAY', 'BELLARY - BAY'),
    ('BGP', 'BHAGALPUR - BGP'),
    ('BKN', 'BIKANER JN - BKN'),
    ('BSP', 'BILASPUR - BSP'),
    ('BINA', 'BINA - BINA'),
    ('BPL', 'BHOPAL - BPL'),
    ('BTI', 'BHATINDA - BTI'),
    ('BKSC', 'BOKARO STL CITY - BKSC'),
    ('BBS', 'BHUBANESHWAR - BBS'),
    ('BWN', 'BURDWAN - BWN'),
    ('BXR', 'BUXAR - BXR'),
    ('CLT', 'CALICUT - CLT'),
    ('CDG', 'CHANDIGARH - CDG'),
    ('MAS', 'CHENNAI - MAS'),
    ('CHTS', 'COCHIN - CHTS'),
    ('CRJ', 'CHITTARANJAN - CRJ'),
    ('CBE', 'COIMBATORE JN - CBE'),
    ('DBG', 'DARBHANGA JN - DBG'),
    ('DJ', 'DARJEELING - DJ'),
    ('DDN', 'DEHRADUN - DDN'),
    ('DHN', 'DHANBAD JN - DHN'),
    ('DWR', 'DHARWAR - DWR'),
    ('DURG', 'DURG - DURG'),
    ('DBRT', 'DIBRUGARH TOWN - DBRT'),
    ('ERS', 'ERNAKULAM - ERS'),
    ('ED', 'ERODE - ED'),
    ('FD', 'FAIZABAD JN - FD'),
    ('FDB', 'FARIDABAD - FDB'),
    ('FBD', 'FARUKHABAD - FBD'),
    ('GAYA', 'GAYA JN - GAYA'),
    ('G', 'GONDIA - G'),
    ('GKP', 'GORAKHPUR JN - GKP'),
    ('GR', 'GULBARGA - GR'),
    ('GNT', 'GUNTUR - GNT'),
    ('GHY', 'GUWAHATI - GHY'),
    ('GWL', 'GWALIOR - GWL'),
    ('HBJ', 'HABIBGANJ - HBJ'),
    ('HWH', 'HOWRAH - HWH'),
    ('HYB', 'HYDERABAD - HYB'),
    ('INDB', 'INDORE JN BG - INDB'),
    ('ET', 'ITARSI - ET'),
    ('JBP', 'JABALPUR - JBP'),
    ('JP', 'JAIPUR - JP'),
    ('JSM', 'JAISALMER - JSM'),
    ('JUC', 'JALANDHAR CITY - JUC'),
    ('JAT', 'JAMMU - JAT'),
    ('JHS', 'JHANSI JN - JHS'),
    ('JU', 'JODHPUR - JU'),
    ('KLK', 'KALKA - KLK'),
    ('CNB', 'KANPUR - CNB'),
    ('CAPE', 'KANYAKUMARI - CAPE'),
    ('KGM', 'KATHGODAM - KGM'),
    ('KPD', 'KATPADI - KPD'),
    ('HWH', 'KOLKATA - HWH'),
    ('KOTA', 'KOTA JN - KOTA'),
    ('KZJ', 'KAZIPET - KZJ'),
    ('LKO', 'LUCKNOW - LKO'),
    ('LDH', 'LUDHIANA - LDH'),
    ('MAO', 'MADGAON - MAO'),
    ('MDU', 'MADURAI - MDU'),
    ('MMC', 'MAHAMANDIR - MMC'),
    ('MAQ', 'MANGALORE - MAQ'),
    ('MMR', 'MANMAD - MMR'),
    ('MTJ', 'MATHURA JN - MTJ'),
    ('MAU', 'MAU JN - MAU'),
    ('MTC', 'MEERUT CITY - MTC'),
    ('MB', 'MORADABAD - MB'),
    ('MGS', 'MUGHAL SARAI - MGS'),
    ('BCT', 'MUMBAI - BCT'),
    ('MYS', 'MYSORE - MYS'),
    ('NGP', 'NAGPUR - NGP'),
    ('NK', 'NASIK - NK'),
    ('NLR', 'NELLORE - NLR'),
    ('NJP', 'NEW JALPAIGURI - NJP'),
    ('NDLS', 'NEW DELHI - NDLS'),
    ('PGT', 'PALGHAT - PGT'),
    ('PNP', 'PANIPAT JN - PNP'),
    ('PTA', 'PATIALA - PTA'),
    ('PNBE', 'PATNA JN - PNBE'),
    ('PUNE', 'PUNE JN - PUNE'),
    ('RBL', 'RAE BARELI JN - RBL'),
    ('RIG', 'RAIGARH - RIG'),
    ('R', 'RAIPUR - R'),
    ('RMM', 'RAMESWARAM - RMM'),
    ('RNC', 'RANCHI - RNC'),
    ('RRME', 'RANCHI ROAD - RRME'),
    ('RTM', 'RATLAM - RTM'),
    ('RN', 'RATNAGIRI - RN'),
    ('REWA', 'REWA - REWA'),
    ('ROK', 'ROHTAK - ROK'),
    ('RKSH', 'RISHIKESH - RKSH'),
    ('RK', 'ROORKEE - RK'),
    ('ROU', 'ROURKELA - ROU'),
    ('SRE', 'SAHARANPUR - SRE'),
    ('SA', 'SALEM - SA'),
    ('SLI', 'SANGLI - SLI'),
    ('STA', 'SATNA - STA'),
    ('SNP', 'SONIPAT - SNP'),
    ('SCL', 'SILCHAR - SCL'),
    ('SML', 'SIMLA - SML'),
    ('SVKS', 'SIVAKASI - SVKS'),
    ('ST', 'SURAT - ST'),
    ('TATA', 'TATANAGAR JN - TATA'),
    ('TNA', 'THANE - TNA'),
    ('TJ', 'THANJAVUR - TJ'),
    ('TPTY', 'TIRUPATI - TPTY'),
    ('TPJ', 'TIRUCHIRAPALLI - TPJ'),
    ('TCR', 'TRICHUR - TCR'),
    ('TVC', 'TRIVANDRUM - TVC'),
    ('TN', 'TUTICORIN - TN'),
    ('UDZ', 'UDAIPUR - UDZ'),
    ('UJN', 'UJJAIN - UJN'),
    ('BRC', 'VADODARA - BRC'),
    ('BSB', 'VARANASI JN - BSB'),
    ('VSG', 'VASCO DA GAMA - VSG'),
    ('BZA', 'VIJAYAWADA JN - BZA'),
    ('VSKP', 'VISHAKAPATNAM - VSKP'),
    ('WL', 'WARANGAL - WL'),
    ('WR', 'WARDHA - WR')
    )

CONNECTION_STATUS = (
  (1, 'FRIEND'),
  (2, 'UNFRIEND'),
  (3, 'BLOCK')
)

HANDICAPPED_CHOICES = (
  ('NO', 'No'),
  ('ORT', 'Orthopaedically Impaired'),
  ('VIS', 'Visually Impaired'),
  ('HEA', 'Hearing Impaired'),
  )

GATE_JAM_CAT_CHOICES = (
  ('GATE', 'GATE'),
  ('JAM', 'JAM'),
  ('CAT', 'CAT'),
  ('CSIR', 'CSIR'),
  ('UNET', 'UGC NET'),
  ('CEED', 'CEED'),
  ('GPAT', 'GPAT'),
  ('INS', 'Inspire'),
  ('ICAR', 'ICAR'),
  ('ICMR', 'ICMR'),
  )


FELLOSHIP_CATEGORY_CHOICES = (
  ('MHRD', 'MHRD'),
  ('UGC', 'UGC'),
  ('CSIR', 'CSIR'),
  ('SPON', 'SPONSRED'),
  ('DST', 'DST'),
  )

PHD_STATUS_CHOICES = (
  ('F', 'Full-Time'),
  ('P', 'Part-Time'),
    )



NATIONALITY_CHOICES = (
    ( "BD" , "Bangladesh" ),
    ( "BE" , "Belgium" ),
    ( "BF" , "Burkina Faso" ),
    ( "BG" , "Bulgaria" ),
    ( "BA" , "Bosnia and Herzegovina" ),
    ( "BB" , "Barbados" ),
    ( "WF" , "Wallis and Futuna" ),
    ( "JT" , "Johnston Island" ),
    ( "BM" , "Bermuda" ),
    ( "BN" , "Brunei" ),
    ( "BO" , "Bolivia" ),
    ( "BH" , "Bahrain" ),
    ( "BI" , "Burundi" ),
    ( "BJ" , "Benin" ),
    ( "BT" , "Bhutan" ),
    ( "JM" , "Jamaica" ),
    ( "BV" , "Bouvet Island" ),
    ( "BW" , "Botswana" ),
    ( "WS" , "Samoa" ),
    ( "BQ" , "British Antarctic Territory" ),
    ( "BR" , "Brazil" ),
    ( "BS" , "Bahamas" ),
    ( "JE" , "Jersey" ),
    ( "WK" , "Wake Island" ),
    ( "BY" , "Belarus" ),
    ( "BZ" , "Belize" ),
    ( "RU" , "Russia" ),
    ( "RW" , "Rwanda" ),
    ( "PC" , "Pacific Islands Trust Territory" ),
    ( "TL" , "Timor-Leste" ),
    ( "RE" , "R\u00e9union" ),
    ( "TM" , "Turkmenistan" ),
    ( "TJ" , "Tajikistan" ),
    ( "RO" , "Romania" ),
    ( "TK" , "Tokelau" ),
    ( "GW" , "Guinea-Bissau" ),
    ( "GU" , "Guam" ),
    ( "GT" , "Guatemala" ),
    ( "GS" , "South Georgia and the South Sandwich Islands" ),
    ( "GR" , "Greece" ),
    ( "GQ" , "Equatorial Guinea" ),
    ( "GP" , "Guadeloupe" ),
    ( "JP" , "Japan" ),
    ( "GY" , "Guyana" ),
    ( "GG" , "Guernsey" ),
    ( "GF" , "French Guiana" ),
    ( "GE" , "Georgia" ),
    ( "GD" , "Grenada" ),
    ( "GB" , "United Kingdom" ),
    ( "GA" , "Gabon" ),
    ( "GN" , "Guinea" ),
    ( "GM" , "Gambia" ),
    ( "GL" , "Greenland" ),
    ( "GI" , "Gibraltar" ),
    ( "GH" , "Ghana" ),
    ( "OM" , "Oman" ),
    ( "TN" , "Tunisia" ),
    ( "JO" , "Jordan" ),
    ( "HR" , "Croatia" ),
    ( "HT" , "Haiti" ),
    ( "HU" , "Hungary" ),
    ( "HK" , "Hong Kong SAR China" ),
    ( "HN" , "Honduras" ),
    ( "SU" , "Union of Soviet Socialist Republics" ),
    ( "HM" , "Heard Island and McDonald Islands" ),
    ( "AE" , "United Arab Emirates" ),
    ( "VE" , "Venezuela" ),
    ( "PR" , "Puerto Rico" ),
    ( "PS" , "Palestinian Territories" ),
    ( "UA" , "Ukraine" ),
    ( "PW" , "Palau" ),
    ( "PT" , "Portugal" ),
    ( "KN" , "Saint Kitts and Nevis" ),
    ( "PZ" , "Panama Canal Zone" ),
    ( "VG" , "British Virgin Islands" ),
    ( "IQ" , "Iraq" ),
    ( "PA" , "Panama" ),
    ( "PF" , "French Polynesia" ),
    ( "PG" , "Papua New Guinea" ),
    ( "PE" , "Peru" ),
    ( "PK" , "Pakistan" ),
    ( "PH" , "Philippines" ),
    ( "PN" , "Pitcairn Islands" ),
    ( "PL" , "Poland" ),
    ( "PM" , "Saint Pierre and Miquelon" ),
    ( "ZM" , "Zambia" ),
    ( "EH" , "Western Sahara" ),
    ( "EE" , "Estonia" ),
    ( "EG" , "Egypt" ),
    ( "ZA" , "South Africa" ),
    ( "EC" , "Ecuador" ),
    ( "IT" , "Italy" ),
    ( "VN" , "Vietnam" ),
    ( "ZZ" , "Unknown or Invalid Region" ),
    ( "SB" , "Solomon Islands" ),
    ( "ET" , "Ethiopia" ),
    ( "SO" , "Somalia" ),
    ( "ZW" , "Zimbabwe" ),
    ( "SA" , "Saudi Arabia" ),
    ( "ES" , "Spain" ),
    ( "ER" , "Eritrea" ),
    ( "ME" , "Montenegro" ),
    ( "MD" , "Moldova" ),
    ( "MG" , "Madagascar" ),
    ( "MF" , "Saint Martin" ),
    ( "MA" , "Morocco" ),
    ( "MC" , "Monaco" ),
    ( "UZ" , "Uzbekistan" ),
    ( "MM" , "Myanmar [Burma]" ),
    ( "ML" , "Mali" ),
    ( "MO" , "Macau SAR China" ),
    ( "MN" , "Mongolia" ),
    ( "MI" , "Midway Islands" ),
    ( "MH" , "Marshall Islands" ),
    ( "MK" , "Macedonia" ),
    ( "MU" , "Mauritius" ),
    ( "MT" , "Malta" ),
    ( "MW" , "Malawi" ),
    ( "MV" , "Maldives" ),
    ( "MQ" , "Martinique" ),
    ( "MP" , "Northern Mariana Islands" ),
    ( "MS" , "Montserrat" ),
    ( "MR" , "Mauritania" ),
    ( "IM" , "Isle of Man" ),
    ( "UG" , "Uganda" ),
    ( "MY" , "Malaysia" ),
    ( "MX" , "Mexico" ),
    ( "IL" , "Israel" ),
    ( "FQ" , "French Southern and Antarctic Territories" ),
    ( "FR" , "France" ),
    ( "IO" , "British Indian Ocean Territory" ),
    ( "FX" , "Metropolitan France" ),
    ( "SH" , "Saint Helena" ),
    ( "AX" , "\u00c5land Islands" ),
    ( "SJ" , "Svalbard and Jan Mayen" ),
    ( "FI" , "Finland" ),
    ( "FJ" , "Fiji" ),
    ( "FK" , "Falkland Islands" ),
    ( "FM" , "Micronesia" ),
    ( "FO" , "Faroe Islands" ),
    ( "NI" , "Nicaragua" ),
    ( "NL" , "Netherlands" ),
    ( "NO" , "Norway" ),
    ( "NA" , "Namibia" ),
    ( "VU" , "Vanuatu" ),
    ( "NC" , "New Caledonia" ),
    ( "NE" , "Niger" ),
    ( "NF" , "Norfolk Island" ),
    ( "NG" , "Nigeria" ),
    ( "NZ" , "New Zealand" ),
    ( "NP" , "Nepal" ),
    ( "NQ" , "Dronning Maud Land" ),
    ( "NR" , "Nauru" ),
    ( "NT" , "Neutral Zone" ),
    ( "NU" , "Niue" ),
    ( "CK" , "Cook Islands" ),
    ( "CI" , "C\u00f4te d\u2019Ivoire" ),
    ( "CH" , "Switzerland" ),
    ( "CO" , "Colombia" ),
    ( "CN" , "China" ),
    ( "CM" , "Cameroon" ),
    ( "CL" , "Chile" ),
    ( "CC" , "Cocos [Keeling] Islands" ),
    ( "CA" , "Canada" ),
    ( "CG" , "Congo - Brazzaville" ),
    ( "CF" , "Central African Republic" ),
    ( "CD" , "Congo - Kinshasa" ),
    ( "CZ" , "Czech Republic" ),
    ( "CY" , "Cyprus" ),
    ( "CX" , "Christmas Island" ),
    ( "CS" , "Serbia and Montenegro" ),
    ( "CR" , "Costa Rica" ),
    ( "PY" , "Paraguay" ),
    ( "CV" , "Cape Verde" ),
    ( "CU" , "Cuba" ),
    ( "CT" , "Canton and Enderbury Islands" ),
    ( "SZ" , "Swaziland" ),
    ( "SY" , "Syria" ),
    ( "KG" , "Kyrgyzstan" ),
    ( "KE" , "Kenya" ),
    ( "SR" , "Suriname" ),
    ( "KI" , "Kiribati" ),
    ( "KH" , "Cambodia" ),
    ( "SV" , "El Salvador" ),
    ( "KM" , "Comoros" ),
    ( "ST" , "S\u00e3o Tom\u00e9 and Pr\u00edncipe" ),
    ( "SK" , "Slovakia" ),
    ( "KR" , "South Korea" ),
    ( "SI" , "Slovenia" ),
    ( "KP" , "North Korea" ),
    ( "KW" , "Kuwait" ),
    ( "SN" , "Senegal" ),
    ( "SM" , "San Marino" ),
    ( "SL" , "Sierra Leone" ),
    ( "SC" , "Seychelles" ),
    ( "KZ" , "Kazakhstan" ),
    ( "KY" , "Cayman Islands" ),
    ( "SG" , "Singapore" ),
    ( "SE" , "Sweden" ),
    ( "SD" , "Sudan" ),
    ( "DO" , "Dominican Republic" ),
    ( "DM" , "Dominica" ),
    ( "DJ" , "Djibouti" ),
    ( "DK" , "Denmark" ),
    ( "DD" , "East Germany" ),
    ( "DE" , "Germany" ),
    ( "YE" , "Yemen" ),
    ( "YD" , "People's Democratic Republic of Yemen" ),
    ( "DZ" , "Algeria" ),
    ( "US" , "United States" ),
    ( "UY" , "Uruguay" ),
    ( "YT" , "Mayotte" ),
    ( "UM" , "U.S. Minor Outlying Islands" ),
    ( "LB" , "Lebanon" ),
    ( "LC" , "Saint Lucia" ),
    ( "LA" , "Laos" ),
    ( "TV" , "Tuvalu" ),
    ( "TW" , "Taiwan" ),
    ( "TT" , "Trinidad and Tobago" ),
    ( "TR" , "Turkey" ),
    ( "LK" , "Sri Lanka" ),
    ( "LI" , "Liechtenstein" ),
    ( "LV" , "Latvia" ),
    ( "TO" , "Tonga" ),
    ( "LT" , "Lithuania" ),
    ( "LU" , "Luxembourg" ),
    ( "LR" , "Liberia" ),
    ( "LS" , "Lesotho" ),
    ( "TH" , "Thailand" ),
    ( "TF" , "French Southern Territories" ),
    ( "TG" , "Togo" ),
    ( "TD" , "Chad" ),
    ( "TC" , "Turks and Caicos Islands" ),
    ( "LY" , "Libya" ),
    ( "VA" , "Vatican City" ),
    ( "VC" , "Saint Vincent and the Grenadines" ),
    ( "VD" , "North Vietnam" ),
    ( "AD" , "Andorra" ),
    ( "AG" , "Antigua and Barbuda" ),
    ( "AF" , "Afghanistan" ),
    ( "AI" , "Anguilla" ),
    ( "VI" , "U.S. Virgin Islands" ),
    ( "IS" , "Iceland" ),
    ( "IR" , "Iran" ),
    ( "AM" , "Armenia" ),
    ( "AL" , "Albania" ),
    ( "AO" , "Angola" ),
    ( "AN" , "Netherlands Antilles" ),
    ( "AQ" , "Antarctica" ),
    ( "AS" , "American Samoa" ),
    ( "AR" , "Argentina" ),
    ( "AU" , "Australia" ),
    ( "AT" , "Austria" ),
    ( "AW" , "Aruba" ),
    ( "IN" , "India" ),
    ( "TZ" , "Tanzania" ),
    ( "AZ" , "Azerbaijan" ),
    ( "IE" , "Ireland" ),
    ( "ID" , "Indonesia" ),
    ( "RS" , "Serbia" ),
    ( "PU" , "U.S. Miscellaneous Pacific Islands" ),
    ( "BL" , "Saint Barth\u00e9lemy" ),
    ( "QA" , "Qatar" ),
    ( "MZ" , "Mozambique" ),
    )


MINORITY_CHOICES = (
    ('NO','No'),
    ('MUS','Muslims'),
    ('SIK','Sikhs'),
    ('CHR','Christians'),
    ('ZOR','Zoroastrians'),
    ('BUD','Buddhists')
    )


COUNTRY_CHOICES = (
    ( "AF" , "Afghanistan" ),
    ( "AL" , "Albania" ),
    ( "DZ" , "Algeria" ),
    ( "AS" , "American Samoa" ),
    ( "AD" , "AndorrA" ),
    ( "AO" , "Angola" ),
    ( "AI" , "Anguilla" ),
    ( "AQ" , "Antarctica" ),
    ( "AG" , "Antigua and Barbuda" ),
    ( "AR" , "Argentina" ),
    ( "AM" , "Armenia" ),
    ( "AW" , "Aruba" ),
    ( "AU" , "Australia" ),
    ( "AT" , "Austria" ),
    ( "AZ" , "Azerbaijan" ),
    ( "BS" , "Bahamas" ),
    ( "BH" , "Bahrain" ),
    ( "BD" , "Bangladesh" ),
    ( "BB" , "Barbados" ),
    ( "BY" , "Belarus" ),
    ( "BE" , "Belgium" ),
    ( "BZ" , "Belize" ),
    ( "BJ" , "Benin" ),
    ( "BM" , "Bermuda" ),
    ( "BT" , "Bhutan" ),
    ( "BO" , "Bolivia" ),
    ( "BA" , "Bosnia and Herzegovina" ),
    ( "BW" , "Botswana" ),
    ( "BV" , "Bouvet Island" ),
    ( "BR" , "Brazil" ),
    ( "IO" , "British Indian Ocean Territory" ),
    ( "BN" , "Brunei Darussalam" ),
    ( "BG" , "Bulgaria" ),
    ( "BF" , "Burkina Faso" ),
    ( "BI" , "Burundi" ),
    ( "KH" , "Cambodia" ),
    ( "CM" , "Cameroon" ),
    ( "CA" , "Canada" ),
    ( "CV" , "Cape Verde" ),
    ( "KY" , "Cayman Islands" ),
    ( "CF" , "Central African Republic" ),
    ( "TD" , "Chad" ),
    ( "CL" , "Chile" ),
    ( "CN" , "China" ),
    ( "CX" , "Christmas Island" ),
    ( "CC" , "Cocos (Keeling), Islands" ),
    ( "CO" , "Colombia" ),
    ( "KM" , "Comoros" ),
    ( "CG" , "Congo" ),
    ( "CD" , "Congo, The Democratic Republic of the" ),
    ( "CK" , "Cook Islands" ),
    ( "CR" , "Costa Rica" ),
    ( "CI" , "Cote D'Ivoire" ),
    ( "HR" , "Croatia" ),
    ( "CU" , "Cuba" ),
    ( "CY" , "Cyprus" ),
    ( "CZ" , "Czech Republic" ),
    ( "DK" , "Denmark" ),
    ( "DJ" , "Djibouti" ),
    ( "DM" , "Dominica" ),
    ( "DO" , "Dominican Republic" ),
    ( "EC" , "Ecuador" ),
    ( "EG" , "Egypt" ),
    ( "SV" , "El Salvador" ),
    ( "GQ" , "Equatorial Guinea" ),
    ( "ER" , "Eritrea" ),
    ( "EE" , "Estonia" ),
    ( "ET" , "Ethiopia" ),
    ( "FK" , "Falkland Islands (Malvinas)," ),
    ( "FO" , "Faroe Islands" ),
    ( "FJ" , "Fiji" ),
    ( "FI" , "Finland" ),
    ( "FR" , "France" ),
    ( "GF" , "French Guiana" ),
    ( "PF" , "French Polynesia" ),
    ( "TF" , "French Southern Territories" ),
    ( "GA" , "Gabon" ),
    ( "GM" , "Gambia" ),
    ( "GE" , "Georgia" ),
    ( "DE" , "Germany" ),
    ( "GH" , "Ghana" ),
    ( "GI" , "Gibraltar" ),
    ( "GR" , "Greece" ),
    ( "GL" , "Greenland" ),
    ( "GD" , "Grenada" ),
    ( "GP" , "Guadeloupe" ),
    ( "GU" , "Guam" ),
    ( "GT" , "Guatemala" ),
    ( "GG" , "Guernsey" ),
    ( "GN" , "Guinea" ),
    ( "GW" , "Guinea-Bissau" ),
    ( "GY" , "Guyana" ),
    ( "HT" , "Haiti" ),
    ( "HM" , "Heard Island and Mcdonald Islands" ),
    ( "VA" , "Holy See (Vatican City State)," ),
    ( "HN" , "Honduras" ),
    ( "HK" , "Hong Kong" ),
    ( "HU" , "Hungary" ),
    ( "IS" , "Iceland" ),
    ( "IN" , "India" ),
    ( "ID" , "Indonesia" ),
    ( "IR" , "Iran, Islamic Republic Of" ),
    ( "IQ" , "Iraq" ),
    ( "IE" , "Ireland" ),
    ( "IM" , "Isle of Man" ),
    ( "IL" , "Israel" ),
    ( "IT" , "Italy" ),
    ( "JM" , "Jamaica" ),
    ( "JP" , "Japan" ),
    ( "JE" , "Jersey" ),
    ( "JO" , "Jordan" ),
    ( "KZ" , "Kazakhstan" ),
    ( "KE" , "Kenya" ),
    ( "KI" , "Kiribati" ),
    ( "KP" , "Korea, Democratic People'S Republic of" ),
    ( "KR" , "Korea, Republic of" ),
    ( "KW" , "Kuwait" ),
    ( "KG" , "Kyrgyzstan" ),
    ( "LA" , "Lao People'S Democratic Republic" ),
    ( "LV" , "Latvia" ),
    ( "LB" , "Lebanon" ),
    ( "LS" , "Lesotho" ),
    ( "LR" , "Liberia" ),
    ( "LY" , "Libyan Arab Jamahiriya" ),
    ( "LI" , "Liechtenstein" ),
    ( "LT" , "Lithuania" ),
    ( "LU" , "Luxembourg" ),
    ( "MO" , "Macao" ),
    ( "MK" , "Macedonia, The Former Yugoslav Republic of" ),
    ( "MG" , "Madagascar" ),
    ( "MW" , "Malawi" ),
    ( "MY" , "Malaysia" ),
    ( "MV" , "Maldives" ),
    ( "ML" , "Mali" ),
    ( "MT" , "Malta" ),
    ( "MH" , "Marshall Islands" ),
    ( "MQ" , "Martinique" ),
    ( "MR" , "Mauritania" ),
    ( "MU" , "Mauritius" ),
    ( "YT" , "Mayotte" ),
    ( "MX" , "Mexico" ),
    ( "FM" , "Micronesia, Federated States of" ),
    ( "MD" , "Moldova, Republic of" ),
    ( "MC" , "Monaco" ),
    ( "MN" , "Mongolia" ),
    ( "MS" , "Montserrat" ),
    ( "MA" , "Morocco" ),
    ( "MZ" , "Mozambique" ),
    ( "MM" , "Myanmar" ),
    ( "NA" , "Namibia" ),
    ( "NR" , "Nauru" ),
    ( "NP" , "Nepal" ),
    ( "NL" , "Netherlands" ),
    ( "AN" , "Netherlands Antilles" ),
    ( "NC" , "New Caledonia" ),
    ( "NZ" , "New Zealand" ),
    ( "NI" , "Nicaragua" ),
    ( "NE" , "Niger" ),
    ( "NG" , "Nigeria" ),
    ( "NU" , "Niue" ),
    ( "NF" , "Norfolk Island" ),
    ( "MP" , "Northern Mariana Islands" ),
    ( "NO" , "Norway" ),
    ( "OM" , "Oman" ),
    ( "PK" , "Pakistan" ),
    ( "PW" , "Palau" ),
    ( "PS" , "Palestinian Territory, Occupied" ),
    ( "PA" , "Panama" ),
    ( "PG" , "Papua New Guinea" ),
    ( "PY" , "Paraguay" ),
    ( "PE" , "Peru" ),
    ( "PH" , "Philippines" ),
    ( "PN" , "Pitcairn" ),
    ( "PL" , "Poland" ),
    ( "PT" , "Portugal" ),
    ( "PR" , "Puerto Rico" ),
    ( "QA" , "Qatar" ),
    ( "RE" , "Reunion" ),
    ( "RO" , "Romania" ),
    ( "RU" , "Russian Federation" ),
    ( "RW" , "RWANDA" ),
    ( "SH" , "Saint Helena" ),
    ( "KN" , "Saint Kitts and Nevis" ),
    ( "LC" , "Saint Lucia" ),
    ( "PM" , "Saint Pierre and Miquelon" ),
    ( "VC" , "Saint Vincent and the Grenadines" ),
    ( "WS" , "Samoa" ),
    ( "SM" , "San Marino" ),
    ( "ST" , "Sao Tome and Principe" ),
    ( "SA" , "Saudi Arabia" ),
    ( "SN" , "Senegal" ),
    ( "CS" , "Serbia and Montenegro" ),
    ( "SC" , "Seychelles" ),
    ( "SL" , "Sierra Leone" ),
    ( "SG" , "Singapore" ),
    ( "SK" , "Slovakia" ),
    ( "SI" , "Slovenia" ),
    ( "SB" , "Solomon Islands" ),
    ( "SO" , "Somalia" ),
    ( "ZA" , "South Africa" ),
    ( "GS" , "South Georgia and the South Sandwich Islands" ),
    ( "ES" , "Spain" ),
    ( "LK" , "Sri Lanka" ),
    ( "SD" , "Sudan" ),
    ( "SR" , "Suriname" ),
    ( "SJ" , "Svalbard and Jan Mayen" ),
    ( "SZ" , "Swaziland" ),
    ( "SE" , "Sweden" ),
    ( "CH" , "Switzerland" ),
    ( "SY" , "Syrian Arab Republic" ),
    ( "TW" , "Taiwan, Province of China" ),
    ( "TJ" , "Tajikistan" ),
    ( "TZ" , "Tanzania, United Republic of" ),
    ( "TH" , "Thailand" ),
    ( "TL" , "Timor-Leste" ),
    ( "TG" , "Togo" ),
    ( "TK" , "Tokelau" ),
    ( "TO" , "Tonga" ),
    ( "TT" , "Trinidad and Tobago" ),
    ( "TN" , "Tunisia" ),
    ( "TR" , "Turkey" ),
    ( "TM" , "Turkmenistan" ),
    ( "TC" , "Turks and Caicos Islands" ),
    ( "TV" , "Tuvalu" ),
    ( "UG" , "Uganda" ),
    ( "UA" , "Ukraine" ),
    ( "AE" , "United Arab Emirates" ),
    ( "GB" , "United Kingdom" ),
    ( "US" , "United States" ),
    ( "UM" , "United States Minor Outlying Islands" ),
    ( "UY" , "Uruguay" ),
    ( "UZ" , "Uzbekistan" ),
    ( "VU" , "Vanuatu" ),
    ( "VE" , "Venezuela" ),
    ( "VN" , "Viet Nam" ),
    ( "VG" , "Virgin Islands, British" ),
    ( "VI" , "Virgin Islands, U.S." ),
    ( "WF" , "Wallis and Futuna" ),
    ( "EH" , "Western Sahara" ),
    ( "YE" , "Yemen" ),
    ( "ZM" , "Zambia" ),
    ( "ZW" , "Zimbabwe" ),
)


